### PR TITLE
Add configurable option

### PR DESCRIPTION
**Pull request by thelucyclub**

### CODE REVIEW

**Comment by thelucyclub** [comment]
> [`_****_`](

- 

- [ ] 1. url

)

**Comment by thelucyclub** [comment]
Why not merge?

**Comment by jasonwynn10** [comment]
there is no need to complicate the plugin further.

**Comment by thelucyclub** [comment]
It's not "complicating" it. It's making it better.

**Comment by thelucyclub** [comment]
Hey can i join LostTeam? (No is okay :disappointed:)

**Comment by jasonwynn10** [comment]
I asked the group, they said it would be fine

**Comment by thelucyclub** [comment]
Cool!

**Pull request closed without merging**
